name: anthrazit
favicon: null
layout_spectrum: 0.8467974602244794
typography_spectrum: 0.5700729738455266
title: Anthrazit Grau
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.09523538500070572
  lightness: 0.29862244706600904
  saturation: 0.6093539097346365
  rhythmicContrast: 0.6349913130979985
purpose: []
